### ISSUE TITLE
Is it work for delayed keyboard from boot?

### ISSUE THREAD

**Issue by dhymasriyanto** [mistine/i8042-keyboard-fix-linux#1]
At first, thanks for making this more sense to me. I have a problem, when I boot my system, the keyboard won't be detected for 10-30 seconds (delayed), and then it can work normally. No problem, I can wait a few seconds to enter my password. But it's annoying when I have to use my laptop in a hurry.

So after surfing the internet, I came across [this](https://askubuntu.com/questions/1366407/keyboard-does-not-work-for-first-few-seconds). I tried it and it worked! I'm also looking for an [explanation of kernel parameters](https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt). But I realized that my capslock and other LED functions are not working.

I decided to look for another solution, and then I found your repo. But in your README it says that it works when we resume our suspended system. Will this work in my case?

**Comment by dhymasriyanto** [comment]
And this is my output of `dmesg | grep i8042`

```
... (Other output)
[    0.920569] serio: i8042 KBD port at 0x60,0x64 irq 1
[    0.920608] serio: i8042 AUX port at 0x60,0x64 irq 12
[    0.940053] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input3
..... (Other output)
[    7.006696] input: SynPS/2 Synaptics TouchPad as /devices/platform/i8042/serio1/input/input9
```

**Comment by mistine** [comment]
Hi there, this was made when I had my old laptop, which had the issue of keyboard/touchpad being frozen after waking up from standby. I’m not sure if this would solve your issue, but of course you can try - edit the script to run on startup with init.d. All it does is it resets the i8042 driver.

As for the keyboard LEDs - that’s caused by using dumbkbd.

**Comment by dhymasriyanto** [comment]
Okay.. Because I use Arch, I think I can't find `init.d` and using `/usr/lib/systemd/system` instead. Then I try to make service from ur script
```
[Unit]
Description=My script
 
[Service]
ExecStart=/usr/lib/systemd/system-shutdown/keyboard-reset
OnStartupSec=0
OnBootSec=0

 
[Install]
WantedBy=multi-user.target
```

I think the scripts run, but it still need time to re-initialize... 

> As for the keyboard LEDs - that’s caused by using dumbkbd.

Yeah, If I'm using dumbkbd it's work normally without initialize time, but cause LED not work (actually I'm looking for a way to make LED still work and make no initialize time needed). 

I already try to using dumbkbd, and run script on boot to restart i8042, but I think it still not working.

**Comment by mistine** [comment]
> Yeah, If I'm using dumbkbd it's work normally without initialize time, but cause LED not work (actually I'm looking for a way to make LED still work and make no initialize time needed).

Try booting with dumbkbd on, then have a logon script that reloads i8042 and turn off dumbkbd. The caviat is that LED won't work before logon. Maybe try loading the script on startup also.
```
#!/bin/sh

rmmod i8042
modprobe i8042 reset=1 dumbkbd=0
```

**Comment by dhymasriyanto** [comment]
Ok i think its work, but the i8042 module still need time to re-initialize, which is still not the best way to me when I'm in hurry. I think for now dumbkbd is fine, even though the led can't be used. :(

**Comment by fromSmolsoft** [comment]
@dhymasriyanto 

Would you elaborate how you made the service to work?  

> ... using `/usr/lib/systemd/system` instead. Then I try to make service from ur script
> 
> ```
> [Unit]
> Description=My script
>  
> [Service]
> ExecStart=/usr/lib/systemd/system-shutdown/keyboard-reset
> OnStartupSec=0
> OnBootSec=0
> 
>  
> [Install]
> WantedBy=multi-user.target
> ```

I try to do basically same thing by adding service that run the script but it keyboard is never becomes responsive after cold start (booting from full shutdown).  I have to use @mistine way to put laptop to sleep  by usb keyboard after booting to enable built in one.  

What i did:
1. put script into
2.  created service `/usr/lib/systemd/system/keyboard-reset.service` with same content as yours expect path to script is `.../system-sleep/keyboard-reset.sh` 
3.  `sudo systemctl daemon-reload' 
4.  `sudo systemctl enable keyboard-reset.service`
5.  `sudo systemd-analyze verify keyboard-reset.service`
     - i get warnings `Uknown key 'OnStartupSec' ...` and same with `'onBootSec'` 
     - this is probably the problem

**Comment by dhymasriyanto** [comment]
@fromSmolsoft 

> I try to do basically same thing by adding service that run the script but it keyboard is never becomes responsive after cold start (booting from full shutdown). 

Have you tried waiting a while after booting? Because as far as I remember the script takes time to run (sorry, I forgot exactly. But if it's still a problem, I can try to execute the script again). Now, I am using [this](https://askubuntu.com/questions/1366407/keyboard-does-not-work-for-first-few-seconds), maybe your problem is same.

**Comment by fromSmolsoft** [comment]
@mistine 
> Have you tried waiting a while after booting? Because as far as I remember the script takes time to run (sorry, I forgot exactly. But if it's still a problem, I can try to execute the script again). Now, I am using [this](https://askubuntu.com/questions/1366407/keyboard-does-not-work-for-first-few-seconds), maybe your problem is same.

Thank you for a reply. 

Yes, I waited for 5-10 minutes:
-  after booting/loading kde login screen in with  kernel commands `i8042.nopnp=1 i8042.dumbkbd=1`  and nothing happened. 
-  after running the original script manually and it doesn't seem to work either.

Only thing that make the keyboard working is to suspend laptop with the [original script](https://github.com/mistine/i8042-keyboard-fix-linux) in `.../system-sleep` as suggested by @dhymasriyanto 

As for suggested solution [this](https://askubuntu.com/questions/1366407/keyboard-does-not-work-for-first-few-seconds), did you switch to GRUB or did you managed to make it work with systemd-boot only?

**Comment by dhymasriyanto** [comment]
sorry if I take a long time to reply, for now I don't use that script anymore. Now I use GURB dumbkbd like the [link](https://askubuntu.com/questions/1366407/keyboard-does-not-work-for-first-few-seconds) I gave.

have you updated the file with
`sudo grub-mkconfig -o /boot/grub/grub.cfg ?`

**Comment by dhymasriyanto** [comment]
@fromSmolsoft 

sorry if I take a long time to reply, for now I don't use that script anymore. Now I use GURB dumbkbd like the [link](https://askubuntu.com/questions/1366407/keyboard-does-not-work-for-first-few-seconds) I gave.

have you updated the file with `sudo grub-mkconfig -o /boot/grub/grub.cfg` ?

**Comment by fromSmolsoft** [comment]
@dhymasriyanto 

> sorry if I take a long time to reply, 

No harm done 👍

>for now I don't use that script anymore.
Now I use GURB dumbkbd like the [link](https://askubuntu.com/questions/1366407/keyboard-does-not-work-for-first-few-seconds) I gave.
> 
> have you updated the file with `sudo grub-mkconfig -o /boot/grub/grub.cfg` ?

I didn't want to install GRUB  as i use Arch default systemd-boot and kinda like it.   Thou systemd-boot also allows kernel params, however those in given  [link](https://askubuntu.com/questions/1366407/keyboard-does-not-work-for-first-few-seconds) don't seem to have any effect whatsoever.   

I just don't understand why reseting i8042 works only when waking up from a sleep mode.     

So for now i boot laptop, make it sleep, that activates keyboard and i can work normally.
